name: publish
on:
    push:
        branches:
            - master
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        name: Publish
        steps:
            - uses: actions/checkout@v4

            - name: npm lint and build
              run: |
                  npm install
                  npm run lint
                  npm run build

            # https://github.com/cycjimmy/semantic-release-action
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              id: semantic
              with:
                  branch: master
                  extra_plugins: |
                      @semantic-release/git
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
